feat: mark sheet export option - exam results
kd-school-erp/erp-ui pull request #402
Opened 2023-04-28 08:40 UTC by sadurga

![image](https://user-images.githubusercontent.com/43200929/235098160-53de9f51-0223-4aec-819a-b2ee238ffa28.png)

2023-05-02 17:30 UTC, kural214 commented
The image not getting exported.
![image](https://user-images.githubusercontent.com/44921344/235740246-65af8874-3370-4a51-b8d9-17b0e3eb4624.png)

Academic year missing
![image](https://user-images.githubusercontent.com/44921344/235740356-a72dc50f-26fd-45ae-aab8-79a0acfaa875.png)

Can you add dialog close button here?
![image](https://user-images.githubusercontent.com/44921344/235740585-376b5426-a33c-452a-88a4-9150111cd204.png)

2023-05-02 17:33 UTC, kural214 requested changes
Please check the comment section

2023-05-03 09:06 UTC, anand-it commented
Close button and academic year added
![image](https://user-images.githubusercontent.com/36123218/235875211-454133b5-bb05-441a-9a80-e05de7058da0.png)
Its already working fine
![image](https://user-images.githubusercontent.com/36123218/235875584-5a85be04-d821-417a-99d5-ac3a46828ace.png)

2023-05-03 13:17 UTC, kural214 approved these changes

2023-05-03 13:17 UTC, merged